[package]
name = "cli-riir"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.7"
git2 = "0.20.1"
log = "0.4.26"
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.12"
